server:
  port: 8035
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: geulium-ieum-dev
  profiles:
    default: local
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  threads:
    virtual:
      enabled: true

  datasource:
    url: ENC(675EpFl+giIhSOmiP5a6wbizsfgNIqSaCteO0j+EBIh9SxidA6dH8YVqW3FJZDOuGF0sTZXwmo/rWFFYUWcxliVEY89qlObRkCGCd7i8tfa3cqUyq8kdN0BAsEobf2iSvkPjjbUPh04zmPqq/TEn0giypDGMQR1iMs3Vhyg0Xi48X5P4u6Smw7IEy85ff3qInckfvDIEZTCBgx1erQDhGA==)
    username: ENC(0f+m8+R4U8fIWkFnVZ6YsLTHDL/PzmlVz+TgyLfJfw+p6RjNmkqRnL2EvuUIeUVO)
    password: ENC(trJ0oO+AqrSdLaOCbCWeLhA5KZFGcsGqlFYgFDpvnPdRMYOYs7E6fV41Jh1mCGY0)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: POOL-GEULIUM-IEUM-DEV

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: false
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  data:
    redis:
      repositories:
        enabled: false
      username: ENC(BYi6WWcXz+T1snzqcje8HhB6J3gbGwMHJMElmIJtCm2664cuWeF9yeBvB3pjeOhc)
      password: ENC(PyzTjUYUCisoaK8Pg0yL6BlSX4RVW6XQUDJdnKiZ1CVTtKLrfPydXwyLPuvDNrqR)
      database: 0
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(vR+VTsmTVzqJGZQ2NXJBW0xDHXX90FdG9JZUwTASR0bENNGgmopKARjpSEK3GxiM)
        nodes:
          - ENC(MT4gcKuXsKPN42h3MlD7qKDek3fkmwpKO+dCPKEIuaM0b5JOYyOtbD+J6fIbckRYidjo7mKk4MKUp/Eu4JDOJw==)
          - ENC(1bfxQU/Ghamelsy9baS4GU7jcwQr8ajdi9EBNV4v+R4138fICPg55x0WqbN808GqbOtv9xXGACzD9cfG2QwbGA==)
          - ENC(zsaqjzwB1Z5UkrabaM1mvdndnrXQ5bKJJpXLfibyFhoyRg3wbIts2K0U4fuHRhJALKpB7q4hwve0ugXOTqI7hA==)
        username: ENC(eYtB/f68vt8T0a/DeK5jgyusOT+FdHyu4deuc1DE5GeWly01igDesPMCgpuRzaqd)
        password: ENC(cWhePRxHe13F+BgeJ7+Kx1T5I0LhDvrpjhfjI+rXCLGmmMGQiK1kze5cXU5usvbj)

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    region: ENC(LfYajKYEj60jLTEEd3Bvk35ZxYSS78pnb22n9G9bYyzwl01nHpJbRQf2eR4LZNQF)
    access-key: ENC(7LGc+CMiCA2XGRzUHuYs0+HbZwTi4aR2BcZR9bHD3adDUIcDZEJhuuJgaqp4sWANBTswYzUUxhaAM3zCigEvEDKYHvX2yW014d2VOTMb7d8=)
    secret-key: ENC(Fcv1u6Gz2iskJSTeuHwFKrgGRHTLPi5N5B+/6aeb4pNoPM1epKCdHllUBb178nx0YT04O3gLqN/QyP65DJMqsqXZAzlmW3anSWLbkF5tc66vpO2x8keDA/MHxhN3Y2AbRbLABXSdZWrV5Scpkv58Tw==)
    s3:
      bucket: ENC(c/vTjbHD67j/i36KW85uZ/ziZM+dFWvi7cFoVQ66fB5q07h72M+CdIOGbv+4n/Gs)
      endpoint: ENC(tXvUmL5ol0hougtyAiMg9L9KOqaGUX3FR0qlekd34nXl44UxUwSGNwBCNFjdLcHKQ4wmQmL1UAp5qd4FgWI+RWWsLHMEL7bR/CbL7Rq/Kdik3Nc8FFSYz3y76JF/O2pipm/eFxOun1lXQrmrmI/QYA==)

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
    default-models-expand-depth: -1
    persist-authorization: true
    display-request-duration: true

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

auth:
  email:
    verification:
      url: http://localhost:5173/auth/verify-email
      maxRetry: 5
      ttl: 10
      coolDown: 60
  password:
    reset:
      url: http://localhost:5173/auth/password-reset
      maxRetry: 5
      ttl: 10
      coolDown: 60
  kakao:
    client-id: ENC(Rs0zoljIVEhpy3nIr4MzG/c0jWvZZhgX+qTd/0xKvFfCxHedBd0qZQENCYMVdNhkPgsZrM6XaJgRAUpwdMV/Qh4iBxmefz6p/ZpST4F18gU=)
    client-secret: ENC(1u7hE8XOjCxd5tS4jkef/FKELNYAcxcXkzEd+YEvMQ962aDVc39d2DFS7ddy/VpT22majusFH0rHrvkMkqlVglG5UIqIWrwmpBk5yOVaHUI=)
  naver:
    client-id: ENC(dubzGGYJPoeDvhr1yCd8+KCLJNfYO5uNXhrY+o4vx9eIw9W8e/E447di9ahsZOLhVREnW9a4h1mo8e2UJ04ydg==)
    client-secret: ENC(mekkbVozpulOHPEyJd8YKDvY2mhHyvJmSLgKxdmQmxvhfmKQ2xt0h+V+WN/dBiDa)

hermes:
  groupKey: b8dd65c8-71ec-467d-b662-b52b9323cda9
  baseUrl: http://hermes:8020
  sendTemplateUrl: ${hermes.baseUrl}/mail/send/template
  familyGroupJoinUrl: http://localhost:5173/family-groups/join?id=

---

server:
  port: 8036

spring:
  application:
    name: geulium-ieum
  config:
    activate:
      on-profile: main

  datasource:
    url: ENC(dUeT1vVII/f3j+A9rJDwDRH1y0c7PwtkUxKdkNSIiv+9xnAICKOkNaTDBmaQsMKrUgfUIxrV32lB57MEUA/B5SoV0C94L2Ix0Yd4Mgx0Q8G8/1TCsvfPjjBwB5yAxFuOo8+cFJllACpSeliwCccOSYw0TTqhJz/JuAGX+8omWXgVvsfRMTaDYn8J2ahBcZxl)
    username: ENC(XsuxpM2HN90SgJLO5rOqSSVUGv8+JfXe4NVWY11Tm8uTFKKL0zfQ2e0xUqrBtIWC)
    password: ENC(awe3B4m2bO+YMKjWr1AP/H1iPBKkfF/v1ABSSnOIjz2mDdiUu18eWxiLo8gcclx0)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: POOL-GEULIUM-IEUM

  data:
    redis:
      username: ENC(zodU8mwT+mQ53RSbCW2UFyEml64fR80d5FQ0JX82PK6BxGBCCSRBbtnZzTqTAoca)
      password: ENC(wrYTGCufPa4f2iNtzqD25NPKYZ6MtSzIdqc+/sTuBxQcQZliCdcaFllq2wxFQHaS)
      database: 1
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(5PGk/suxuMqjCxXzu13Pp8kr96CdpVNHzTnuToRUJyLm5bDw6U9YK8kCMcQuH7Ew)
        nodes:
          - ENC(idXTOOTY7hbjX1dZZbyXnUxCT2CQIDZOt052rNSY1w1EeYZ8WLzhtx4SUE76LCIz9ziuQCih46MP/4Y05/vhdw==)
          - ENC(qmc2CWhgqmA9eRVG+t55i6d8B54Eer59XNODDK+EEfyVXq15KuKXwU/tgnEJDz5uY0QtKbojXSP26nMIPln7zQ==)
          - ENC(Mc22E11C9Rxn9BIxmzK5dOsEUAc8Ac0JG4FfoHAsnI9s8sAlKVqnh7zlgUKQuq5pwF6fth+MlgIiz8f/ldmafQ==)
        username: ENC(bxkjtESRmC+tzp31mqb8p/bsbx2lzDKKchZmpEk+CYMsLF6LEuyEUd9AkLCjkL3H)
        password: ENC(CZT5F+0sE1cjgSM7fAlrtK4nwseLOFr1wZwRaXbyFx08/z6hF5yZ80P7fLEz8Jw2)

cloud:
  aws:
    s3:
      bucket: ENC(q/Rn4RhhwH3LtLrtqtwaG5jK9NOD4weLeiHuLfYUPLXLowLegYv+PRnpdWJrYUge)

# SpringDoc(OpenAPI/Swagger) — 운영(main) 프로필에서는 비활성화
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false