server:
  port: 8035
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: geulium-ieum-dev
  profiles:
    default: local
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  threads:
    virtual:
      enabled: true

  datasource:
    url: ENC(WcA9vvuljUKSSx3kRZcddbXjnPdwMLmd1dNpylyONPvH4epKqZRS74ieF93qydGtXsJO6hA6cEccw12io0SxMoNKDFCetv+RkrnxpA2FyUpfcY76ikg51MfY0tpMUB6rOc+UozO8BII8HyFdReBxx0DWUSwTRCgnC7ZyJSVcwFNK5DEL1XqNpTHfX9IXM6BJTja9xWgJcMlV+AcYF7UHWA==)
    username: ENC(4Q6UnWPLx8qOX3w4u2uWhpDlhBpysHylpwy5w8pBAiBiYaPft59QNJ2BhJJ4U3iK)
    password: ENC(l3Tz33qwarDSUgdN5Na6FV44EgXyR33loQ3SQY2uU52UM9UQPg2rsnw9crZ4/qNB)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: POOL-GEULIUM-IEUM-DEV

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: false
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  data:
    redis:
      repositories:
        enabled: false
      username: ENC(L/lDANjUDm/FC2uckz0XHz7HjqLk2db3DaOlXSgE3Lps4wl7dtt4GfQD3k+qkuSS)
      password: ENC(zhHAp6+YNaq6M7Hdge4UG6nqZVUV4ONjYs/HQuJ71E9VQlMTqKXTQhTZNef7JrwJ)
      database: 0
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(u7u0LNfpz6wj/xZ/GaDKWH1K4HmJc9/dpsWjyxlwLLGD1bKCAbrQdzqjlZWdUkNX)
        nodes:
          - ENC(yH+QAncAAvXs+s1ltsNltTwezWD6QDaaL6yxPXNGUnuD3T/W3CBeEUjVSClFfNdDotJjNQlxLyALMR+j3izcvA==)
          - ENC(Nkg86e8O6bcQNJ08s4K2CfSDpQ5EWjf8TtGIIFrVUCa3MYYGTxG7j6yEwXoRebcPU16+AwmiodC/SpytSbOsaw==)
          - ENC(ah+sjmahOkN9qiKHmCuEGRybTizS92ow8eMILIh2G8tcav0Pwu09TPRt/7bPgPpFSyHQXEj/bK5rkrP2MkOfhg==)
        username: ENC(BBuM2hJx18g6l9qW7hBvIIVPscxLnmu68JagmEtnxduZsXOfQ30hD5uu7TMwVKAR)
        password: ENC(kMK8p2VfBWKmOkph4iEdNccre6+4U55a96USLw9Htc1WxGztlSViDmwdT1gBxaHc)

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    region: ENC(H2gnyFZJUzmzcfiMVw4qHaUT44iJ6Q2+oBVJZ92HMyItxdQfcX9uhJZkmnUSkaOh)
    access-key: ENC(6vrCS5vKR0FLOFHAGpqXxyPKor09B41u3AWg+zIT8OeaDbm27MBaqpv6A2pgh8ttj4eLQkdGf421bFweGiCLDYYw4SQb/kIqjybokbyXGn4=)
    secret-key: ENC(7bUivlP8cyM2wFw0kFiFyGiH6nFy+tTzE+DS0J6aAeO79nB0zANlnvn+gA/e2zY8Qy16lQXRx/OIoYxscLcT2W/9BLXTa2JsNbyCbKN73tliFvzqO8erY3WnAQWAv7OBxy1LOZMkLkf+xoHVlwmYqg==)
    s3:
      bucket: ENC(/w3YlvBV37mFNil73OVly1Jskr9+BheEnCeJvvlw1v8lVtHqO6cFwFfN3eaMHxvl)
      endpoint: ENC(RXkvYm2DdgSesG3fTU3Le98yJKC1SyawvctDDGA8c5Z4eXr0LEmi9vyZRR/LGjPsLkJUfpDPdmSeYTg/JzMZVg3EVpr2P03uf7iWRFXp8lrRPUEYNkCp+Z7OR46BO4/itJwIAEyiVNW3s3O/LpKzmQ==)

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
    default-models-expand-depth: -1
    persist-authorization: true
    display-request-duration: true

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

auth:
  email:
    verification:
      url: http://localhost:5173/auth/verify-email
      maxRetry: 5
      ttl: 10
      coolDown: 60
  password:
    reset:
      url: http://localhost:5173/auth/password-reset
      maxRetry: 5
      ttl: 10
      coolDown: 60
  kakao:
    client-id: ENC(BtDINEIHuhzspkZ6TKPQgWwtj7fglHDyoIppWPBZkF598rL2RvyRbaFP7N/Eded0r1LiGXHC7AgqG7E36bNJ4h9FQR7dSk6gW6+b85qkhZI=)
    client-secret: ENC(wDzJbF8I1N1bhGu5SQnH1wJTAtpGoDFz3wT8a50hoQWXXr1p2Jc8DLLdSGjtnZZ9rJZ+Sto12hIC+TeFp2UscZLRwFuY+aeN4gsofVRMTi4=)
  naver:
    client-id: ENC(fLWKExBM5nOmoxIG3fn0nKP18sQU/17srOkN4HzgbK6N7rqzTMNYFq3LetB2ETURYLv/VxJSpz3VAQnSiqJU9g==)
    client-secret: ENC(MIOCZwqFj2PDBSyY9M9BKSNhwb9Yeyl8UXT2Z0xHtG/s9CNDoxNjie4cmo00BUW8)

hermes:
  groupKey: b8dd65c8-71ec-467d-b662-b52b9323cda9
  baseUrl: http://hermes:8020
  sendTemplateUrl: ${hermes.baseUrl}/mail/send/template
  familyGroupJoinUrl: http://localhost:5173/family-groups/join?id=

---

server:
  port: 8036

spring:
  application:
    name: geulium-ieum
  config:
    activate:
      on-profile: main

  datasource:
    url: ENC(XfnnEXZAUPupr0NFQnSB/81miIB+rRn6g4k7g8qfEYoT0nwhF88J7wXCgtc1EZu8fPEuxFGuEb5NZMOaLZZlquyhZO9kIcz7dyabdz0G08ZjnrWckkRJwWqMHiWk/HRH1cOazFGkrzque8ojFZxzleaRKLPrOb1XexEvdAYz9HP+vkFV+3ppRqSOomtMOVE+54RxRwpviwL09mNxAnYktA==)
    username: ENC(xk/qDBX0f/Yq+qNUmdlylNcg1s14lLvUSG/Apoj3TrHv6Wdep5fYpVs63jXKUPLk)
    password: ENC(Rbdcu03PJdXfhC4TZLZVYhHZpEVBoRNCYwKRBpnKPWDQr4fA4JBIQQpqIqlQozVd)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: POOL-GEULIUM-IEUM

  data:
    redis:
      username: ENC(rqz9TBGLKGS1Sl1FccPNvft7w7mvKWjmdMkBBe+Dkz2wnidMdNUFoI9qxTV7Im4V)
      password: ENC(HhFF+rblVc6lLucsNp/OyWESoXcjvWU2ptTd4S4vHqbfZPD4Rzu6I/fC5Mv4el5l)
      database: 1
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(+TtxDgLAa1OAKBzx/N+SxCUDnaZr/a40DEpUzXEgGAQlbpSy6z/MVaHPJDutSWrA)
        nodes:
          - ENC(2MgnJMawNcrOvmAelBN9dLZ0GaYGLsP/QkrDVF5RFsTYaDREzBFv5WdgCmd7t4uMPJzJkCwfhrC9SBB2p/XEGg==)
          - ENC(tliJJp/hZXtTa2OG9Y4JVcqb/5BSmlQ3qIPjC5jOp+plHpHZL+Eicke20tg1j0pC0/3QAf2xzlIMnTtbIn8yHA==)
          - ENC(KSjfYu/yYQ13RByz/ZV8lPan9T5SDNoeCD7/pibRsY6WNEhyFEktP7HXniGMrENLg5aDMEhMh2270MJhiCqEYA==)
        username: ENC(+N8woGNVyub7QEeCSU1YAG0HZ7LDIArvj9zoQeQcKJEBeVhAulbLcmypv7MetCD3)
        password: ENC(6EdEJSPVNR2O1jP7/+HzRzEZy2F5su7QkgN/tb4SZZL75zZzKbKlpLoLadc2H8e9)

cloud:
  aws:
    s3:
      bucket: ENC(9hiIXyuzlgXH7CDKlO1Itw2ftCHXfsO6V6aj2agC7vVyj8VAQ6DjSDO7LBPt7Eek)

# SpringDoc(OpenAPI/Swagger) — 운영(main) 프로필에서는 비활성화
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false